{% set name = "rr_cache" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 34b1f09644ed10a4f36027e80fa89fe2b11c0a8c795c6d4ce8dabec3a681e336

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} setup.py install

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - brs_utils >=1.26.0
    - requests
    - rdkit
    - colored
    - pandas

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: RetroRules Cache
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - ramez17khaled
