{% set name = "rr_cache" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8b8f183ce96eb6671c518a10e565dbd0268279e0be1abfd9aa28987946c2d918

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - brs_utils
    - requests
    - rdkit
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: RetroRules Cache
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
