{% set name = "rr_cache" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 70ff7bf9c30025d0c1336227447b2e2456b6c0245257ac0286294d79f9d124b4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - brs_utils >=1.26.0
    - requests
    - rdkit
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: RetroRules Cache
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
    - ramez17khaled
