{% set name = "rr_cache" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..
  url: https://github.com/brsynth/{{ name }}/archive/{{ version }}.tar.gz
  sha256: d0a554e5928125da01649b98890091563c6ddef9c4842bf62712bc689cab61a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - brs_utils >=1.22.1
    - requests
    - rdkit
    - colored

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: RetroRules Cache
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - breakthewall
